### ISSUE TITLE
Create an event object parser

### ISSUE THREAD

**Issue by LouGel** [carbonable-labs/dna_indexer#1]
**Description**  
---  
Implement a script that parses starknet vent  events into human-readable objects, making them compatible with PostgreSQL tables. The script will ensure smooth conversion of data types (e.g., `u256` → `numeric`, `address` → `varchar(66)`(that includes the 0x), etc.), including selector handling.  

**Acceptance Criteria**  
---  

- [ ] Create a script that:  
  - Automatically parses events into objects with human-readable values.  
  - Maps values to PostgreSQL-compatible types (`u256` → `numeric`, `address` → `varchar(66)`, etc.).  
  - Includes event selectors in the parsed output.  

- [ ] Scan all `contract_class` files containing ABI in a repository.  
  - Generate a general parser to handle ABI structures.  
  - Ensure the parser dynamically calls the appropriate object's `create` function.  
 - [ ] Give me some tests

**Additional Context**  
---  
The script should be modular, clean, and easy to maintain, ensuring seamless integration and usability.
You don't need to push on psql db , just  use the logs to debug

**Comment by JoE11-y** [comment]
I’d like to resolve this.

**Comment by jrmncos** [comment]
hey team, I'm not so sure how to implement this one, but it's seems a funny and hard ticket. I already applied to this one https://github.com/carbonable-labs/carbon-locker/issues/1 (And I prefer that one) but I can tackle this one too.

**Comment by julienbrs** [comment]
Hi, I've assigned that issue to @JoE11-y as they were the first one to ask. You can ping me if you got any question, and please join TG if not already done: https://t.me/carbonableOD

**Comment by JoE11-y** [comment]
Thank you @julienbrs.

Will join now. 💪
